# Generated by Django 4.1 on 2023-11-21 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
