# Generated by Django 4.1 on 2023-11-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_remove_message_author_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.TextField(default="anonym"),
            preserve_default=False,
        ),
    ]
